version: '2'
services:
  node:
    build: .
    command: bash
    container_name: node
    volumes:
      - .:/usr/app/chat:delegated
    ports:
      - 8080:8080
    tty: true
    environment:
      - PORT = 8080
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
